src/objects/BLP_Course__c.object
<CustomObject>
    <fields>
        <fullName>BLP_Course_Format__c</fullName>
        <label>Course Format</label>
        <picklist>
            <picklistValues>
                <fullName>On-demand Content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Face to Face</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Virtual Classroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eLearning</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BLP_Course_Name__c</fullName>
        <description>LABEL_VALUE_TITLE Integration Field Mapping Name</description>
        <label>Course Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BLP_Description__c</fullName>
        <description>LABEL_VALUE_DESC Mapping Id From Informatica</description>
        <label>Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>BLP_Mandatory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mandatory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BLP_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replaced</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BLP_Training_Categories__c</fullName>
        <label>Training Categories</label>
        <picklist>
            <picklistValues>
                <fullName>Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health and Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GXP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Soft Skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>My Job</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Course Seq No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/BLP_Course_To_Training_Path__c.object
<CustomObject>
    <fields>
        <fullName>BLP_Course__c</fullName>
        <label>Course</label>
        <referenceTo>BLP_Course__c</referenceTo>
        <relationshipLabel>Course To Training Paths</relationshipLabel>
        <relationshipName>Course_To_Training_Paths</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BLP_Training_Path__c</fullName>
        <label>Training Path</label>
        <referenceTo>BLP_Training_Path__c</referenceTo>
        <relationshipLabel>Course To Training Paths</relationshipLabel>
        <relationshipName>Course_To_Training_Paths</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Course To Training Path</label>
    <nameField>
        <displayFormat>CT-{00000000}</displayFormat>
        <label>Sequence Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course To Training Paths</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BLP_Training_Dates__c.object
<CustomObject>
    <fields>
        <fullName>BLP_Course__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Course</label>
        <referenceTo>BLP_Course__c</referenceTo>
        <relationshipLabel>Training Dates</relationshipLabel>
        <relationshipName>Training_Dates</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BLP_Training_Date_Time__c</fullName>
        <label>Training Date Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Training Dates</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Training Dates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Dates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/BLP_Training_Path__c.object
<CustomObject>
    <fields>
        <fullName>BLP_Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>BLP_Mandatory__c</fullName>
        <label>Mandatory</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BLP_User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Training_Paths</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Training Path</label>
    <nameField>
        <label>Training Path Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Paths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BLP_User_To_Course__c.object
<CustomObject>
    <fields>
        <fullName>BLP_Course_Name__c</fullName>
        <formula>BLP_Course__r.BLP_Course_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Course Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BLP_Course__c</fullName>
        <label>Course</label>
        <referenceTo>BLP_Course__c</referenceTo>
        <relationshipLabel>User To Course</relationshipLabel>
        <relationshipName>User_To_Course</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BLP_Date_of_Completion__c</fullName>
        <label>Date of Completion</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BLP_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unregistered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered Without Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlisted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed Waitlisted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BLP_Training_Dates__c</fullName>
        <label>Training Dates</label>
        <referenceTo>BLP_Training_Dates__c</referenceTo>
        <relationshipLabel>User To Course</relationshipLabel>
        <relationshipName>User_To_Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BLP_User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_To_Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User To Course</label>
    <nameField>
        <displayFormat>UC-{000000000}</displayFormat>
        <label>Sequence Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User To Course</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BLP_MyTrainingComponentController.cls
Public With Sharing Class BLP_MyTrainingComponentController{
    
    Public Map<String, UserToCourseWrapper> courseToUserToCourseMap {get;set;}
    Public List<TrainingPathWrapper> TrainingPathWrapperList {get;set;}
    Public List<BLP_UtilityController.AdditionalSubscribedCourses> AddidtionalCoursesList {get;set;}
    public string selectedCourseId{get;set;}
    
    Public BLP_MyTrainingComponentController() {
        selectedCourseId = '';
        BLP_UtilityController helper = new BLP_UtilityController();
        AddidtionalCoursesList = helper.getListOfSubscribedCourse();
        TrainingPathWrapperList = new List<TrainingPathWrapper>();
        courseToUserToCourseMap = new Map<String, UserToCourseWrapper>();
        getCurrentUserTrainingPath();
    }
    
    Public void getCurrentUserTrainingPath() {
      Id currentUserId = UserInfo.getUserId();
      Set<Id> courseIdSet = new Set<Id>();
      Map<String, List<String>> trainingPathToCoursesListMap = new Map<String, List<String>>();
      Map<Id, BLP_Training_Path__c> myTrainingPathMap = new Map<Id, BLP_Training_Path__c>([SELECT Id, Name, BLP_Description__c, (SELECT Id, BLP_Course__c 
                                                                            FROM Course_To_Training_Paths__r) 
                                                          FROM BLP_Training_Path__c 
                                                          WHERE BLP_User__c = :currentUserId]);
      
      if (myTrainingPathMap.size() > 0) {
        for (BLP_Training_Path__c trainPath : myTrainingPathMap.values()) {
          for (BLP_Course_To_Training_Path__c courseToTrain : trainPath.Course_To_Training_Paths__r) {
            courseIdSet.add(courseToTrain.BLP_Course__c);
            if (!trainingPathToCoursesListMap.containsKey(trainPath.Id)) {
              trainingPathToCoursesListMap.put(trainPath.Id, new List<String>());
            }
            trainingPathToCoursesListMap.get(trainPath.Id).add(courseToTrain.BLP_Course__c);
          }
        }
        system.debug('trainingPathToCoursesListMapp '+trainingPathToCoursesListMap);
        Map<Id, BLP_Course__c> myCoursesMap = new Map<Id, BLP_Course__c>([SELECT Id, Name, BLP_Mandatory__c, BLP_Course_Name__c, BLP_Course_Format__c, BLP_Training_Categories__c,BLP_Status__c,
                                                                                (SELECT ID, BLP_User__c, BLP_Status__c, BLP_Date_of_Completion__c, 
                                                                                        BLP_Training_Dates__r.BLP_Training_Date_Time__c
                                                                                 FROM User_To_Course__r WHERE BLP_User__c = :currentUserId) 
                                                                          FROM BLP_Course__c 
                                                                          WHERE Id IN :courseIdSet]);
        system.debug('myCoursesMapp '+myCoursesMap); 
        
        for (BLP_Course__c course : myCoursesMap.values()) {
            for (BLP_User_To_Course__c userToCourse : course.User_To_Course__r) {
              courseToUserToCourseMap.put(course.Id, new UserToCourseWrapper(userToCourse));
            }
            if(course.User_To_Course__r.size() <= 0) {
              courseToUserToCourseMap.put(course.Id, new UserToCourseWrapper(null));
            }
        }
        system.debug('courseToUserToCourseMapp '+courseToUserToCourseMap); 
        
        for (String trainPathId : trainingPathToCoursesListMap.keySet()) {
          Integer totalCourseCount = 0;
          Integer mandatoryCourseCount = 0;
          Integer completedCourseCount = 0;
          Map<String, List<BLP_Course__c>> courseCategoryToCourseListMap = new Map<String, List<BLP_Course__c>>();
          for(String courseId : trainingPathToCoursesListMap.get(trainPathId)){
              totalCourseCount++;
              if (myCoursesMap.get(courseId).BLP_Mandatory__c == true) {
                mandatoryCourseCount++;
              }
              if (courseToUserToCourseMap.get(courseId).status == 'Completed') {
                completedCourseCount++;
              }
              String courseCategory = myCoursesMap.get(courseId).BLP_Training_Categories__c;
              if (!courseCategoryToCourseListMap.containsKey(courseCategory)) {
                courseCategoryToCourseListMap.put(courseCategory, new List<BLP_Course__c>());
              }
              courseCategoryToCourseListMap.get(courseCategory).add(myCoursesMap.get(courseId));
          }
          TrainingPathWrapperList.add(new TrainingPathWrapper(myTrainingPathMap.get(trainPathId), totalCourseCount, mandatoryCourseCount, 
                                                              completedCourseCount, courseCategoryToCourseListMap));
        }
        system.debug('TrainingPathWrapperListt '+TrainingPathWrapperList);
      } else {
        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO, Label.BLP_No_Training_Path);
        ApexPages.addMessage(myMsg);
      }
    }
    
    public pagereference redirectUser(){
        if(selectedCourseId != null && selectedCourseId != ''){
            BLP_UtilityController helper = new BLP_UtilityController();
            return helper.redirectUserCommon(selectedCourseId);
        }
        return null;
    }
    
    Public Class TrainingPathWrapper {
      Public BLP_Training_Path__c trainPath {get;set;}
      Public Decimal totalCourseCount {get;set;}
      Public Integer mandatoryCourseCount {get;set;}
      Public Decimal completedCourseCount {get;set;}
      Public Decimal completedCoursePercent {get;set;}
      Public Map<String, List<BLP_Course__c>> courseCategoryToCourseListMap {get;set;}
      Public TrainingPathWrapper(BLP_Training_Path__c trainPath, Decimal totalCourseCount, Integer mandatoryCourseCount, 
                                 Decimal completedCourseCount, Map<String, List<BLP_Course__c>> courseCategoryToCourseListMap) {
        this.trainPath = trainPath;
        this.totalCourseCount = totalCourseCount;
        this.mandatoryCourseCount = mandatoryCourseCount;
        this.completedCourseCount = completedCourseCount;
        this.completedCoursePercent = completedCourseCount/totalCourseCount;
        this.courseCategoryToCourseListMap = courseCategoryToCourseListMap;
      }
  }
      
      Public Class UserToCourseWrapper {
          Public BLP_User_To_Course__c userToCourse {get;set;}
          Public String status {get;set;}
          Public DateTime trainingDate {get;set;}
          
          Public UserToCourseWrapper(BLP_User_To_Course__c userToCourse) {
            this.userToCourse = userToCourse;
            if(userToCourse != null) {
              this.status = Label.BLP_In_Progress;
              this.trainingDate = userToCourse.BLP_Training_Dates__r.BLP_Training_Date_Time__c;
              if (userToCourse.BLP_Date_of_Completion__c != null) {
                  this.status = Label.BLP_Completed;
              }
            } else {
              this.status = Label.BLP_Not_Registered;
            }
          }
    }
    
}