src/objects/BLP_Course__c.object
<CustomObject>
    <fields>
        <fullName>BLP_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replaced</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Course Seq No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/BLP_Prework_Postwork__c.object
<CustomObject>
    <fields>
        <fullName>BLP_Completion_Date__c</fullName>
        <label>Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BLP_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Complete</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BLP_User_To_Course__c</fullName>
        <label>User To Course</label>
        <referenceTo>BLP_User_To_Course__c</referenceTo>
        <relationshipLabel>Prework Postwork</relationshipLabel>
        <relationshipName>Prework_Postwork</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Prework Postwork</label>
    <nameField>
        <label>Prework Postwork Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prework Postwork</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BLP_Training_Dates__c.object
<CustomObject>
    <fields>
        <fullName>BLP_Course__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Course</label>
        <referenceTo>BLP_Course__c</referenceTo>
        <relationshipLabel>Training Dates</relationshipLabel>
        <relationshipName>Training_Dates</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BLP_Number_of_Attendees_Registered__c</fullName>
        <label>Number of Attendees Registered</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Training Dates</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Training Dates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Dates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/BLP_User_To_Course__c.object
<CustomObject>
    <fields>
        <fullName>BLP_Course__c</fullName>
        <label>Course</label>
        <referenceTo>BLP_Course__c</referenceTo>
        <relationshipLabel>User To Course</relationshipLabel>
        <relationshipName>User_To_Course</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BLP_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unregistered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered Without Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlisted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed Waitlisted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BLP_Training_Dates__c</fullName>
        <label>Training Dates</label>
        <referenceTo>BLP_Training_Dates__c</referenceTo>
        <relationshipLabel>User To Course</relationshipLabel>
        <relationshipName>User_To_Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BLP_User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_To_Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User To Course</label>
    <nameField>
        <displayFormat>UC-{000000000}</displayFormat>
        <label>Sequence Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User To Course</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BLP_CourseDetailRegisteredController.cls
Public class BLP_CourseDetailRegisteredController{
    
    public BLP_UtilityController.AdditionalSubscribedCourses subscribedCourseRegistered{get;set;}
    public string courseId;
    public string registerOrWaitlist{get;set;}
    public list<BLP_UtilityController.prePostWork> preWorkList{get;set;}
    public list<BLP_UtilityController.prePostWork> postWorkList{get;set;}
    
    public BLP_CourseDetailRegisteredController(){
        registerOrWaitlist = '';
        courseId = Apexpages.currentPage().getParameters().get('courseId');
        BLP_UtilityController helper = new BLP_UtilityController();
        subscribedCourseRegistered = helper.getSubscribedCourse(courseId);
        preWorkList = helper.prePostWorkList(courseId,'Prework');
        postWorkList = helper.prePostWorkList(courseId,'Postwork');
    }
    
    public void updatePreWork(){
        if(preWorkList != null && preWorkList.size() > 0){
            list<BLP_Prework_Postwork__c> workListToUpdate = new list<BLP_Prework_Postwork__c >();
            for(BLP_UtilityController.prePostWork work : preWorkList){
                BLP_Prework_Postwork__c prePostTemp = new BLP_Prework_Postwork__c();
                prePostTemp.id = work.id;
                
                if(work.completed){
                    prePostTemp.BLP_Status__c = 'Complete';
                    prePostTemp.BLP_Completion_Date__c = System.today();
                }
                else{
                    prePostTemp.BLP_Status__c = 'Not Complete';
                    prePostTemp.BLP_Completion_Date__c = null;
                }
                workListToUpdate.add(prePostTemp);
            }
            if(workListToUpdate != null && workListToUpdate.size() > 0){
                update workListToUpdate;
            }
        }     
    }
    
    public void updateePostWork(){
        if(postWorkList != null && postWorkList.size() > 0){
            list<BLP_Prework_Postwork__c> workListToUpdate = new list<BLP_Prework_Postwork__c >();
            for(BLP_UtilityController.prePostWork work : postWorkList){
                BLP_Prework_Postwork__c prePostTemp = new BLP_Prework_Postwork__c();
                prePostTemp.id = work.id;
                
                if(work.completed){
                    prePostTemp.BLP_Status__c = 'Complete';
                    prePostTemp.BLP_Completion_Date__c = System.today();
                }
                else{
                    prePostTemp.BLP_Status__c = 'Not Complete';
                    prePostTemp.BLP_Completion_Date__c = null;
                }
                workListToUpdate.add(prePostTemp);
            }
            if(workListToUpdate != null && workListToUpdate.size() > 0){
                update workListToUpdate;
            }
        }    
    }
    
    public pagereference DeregisterUser(){
        if(courseId != null){
            list<BLP_User_To_Course__c> ustList = [select id, name, BLP_Course__c, BLP_Training_Dates__c from BLP_User_To_Course__c where BLP_User__c =: UserInfo.getUserId() AND BLP_Course__c =: courseId order by lastModifiedDate desc limit 1];
            if(ustList != null && ustList.size() > 0){
                if(ustList[0].BLP_Training_Dates__c != null){
                    if(registerOrWaitlist == 'Registered'){
                        ustList[0].BLP_Status__c = 'Unregistered';
                        list<BLP_Training_Dates__c> trainingDatesList = [select id, name, BLP_Number_of_Attendees_Registered__c, BLP_Course__c from BLP_Training_Dates__c where id =: ustList[0].BLP_Training_Dates__c];
                        if(trainingDatesList != null && trainingDatesList.size() > 0){
                            if(trainingDatesList[0].BLP_Number_of_Attendees_Registered__c != null){
                                trainingDatesList[0].BLP_Number_of_Attendees_Registered__c = trainingDatesList[0].BLP_Number_of_Attendees_Registered__c - 1;
                            }
                            update trainingDatesList;
                            if(trainingDatesList[0].BLP_Course__c != null){
                                list<BLP_Course__c> courseList = [select id, name,(select id, name, BLP_User__c from User_To_Course__r where BLP_status__c = 'Waitlisted') from BLP_Course__c where id =: trainingDatesList[0].BLP_Course__c];
                                List<Messaging.SingleEmailMessage> msgList= new List<Messaging.SingleEmailMessage>();
                                for(BLP_Course__c cour : courseList){
                                    for(BLP_User_To_Course__c user : cour.User_To_Course__r){
                                        if(user.BLP_User__c != null){
                                            list<EmailTemplate> template = [select id from EmailTemplate where DeveloperName='BLP_Waitlist_Available'];
                                            if(template != null && template.size() > 0){
                                                Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();
                                                msg.setTemplateId(template[0].id);
                                                msg.setTargetObjectId(user.BLP_User__c);
                                                msg.setSaveAsActivity(false);
                                                msgList.add(msg);
                                            }
                                        }
                                    }
                                }
                                if(msgList != null && msgList.size() > 0){
                                    Messaging.sendEmail(msgList);
                                }
                            }
                        }
                    }
                    else if(registerOrWaitlist == 'Waitlisted'){
                        ustList[0].BLP_Status__c = 'Removed Waitlisted';
                    }
                    update ustList;
                }
                
                PageReference pg = page.BLP_MyTraining;
                pg.setRedirect(true);
                return pg;
            } 
        }
        return null;
    }
}