src/objects/BLP_Course__c.object
<CustomObject>
    <fields>
        <fullName>BLP_Course_Name__c</fullName>
        <description>LABEL_VALUE_TITLE Integration Field Mapping Name</description>
        <label>Course Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Course Seq No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/BLP_Course_To_Curriculum__c.object
<CustomObject>
    <fields>
        <fullName>BLP_Course__c</fullName>
        <description>QUAL_ID from SuccesFactors Integration</description>
        <label>Course</label>
        <referenceTo>BLP_Course__c</referenceTo>
        <relationshipLabel>Course To Curriculum</relationshipLabel>
        <relationshipName>Course_To_Curriculum</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BLP_Curriculum__c</fullName>
        <description>CPNT_ID From SuccessFactors Integration</description>
        <label>Curriculum</label>
        <referenceTo>BLP_Curriculum__c</referenceTo>
        <relationshipLabel>Course To Curriculum</relationshipLabel>
        <relationshipName>Course_To_Curriculum</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Course To Curriculum</label>
    <nameField>
        <label>Course To Curriculum  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course To Curriculum</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BLP_Curriculum__c.object
<CustomObject>
    <fields>
        <fullName>BLP_Curriculum_Title__c</fullName>
        <description>QUAL_TITLE from SuccessFactors Integration</description>
        <label>Curriculum Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Curriculum</label>
    <nameField>
        <label>Curriculum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curriculum</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BLP_CreateTrainingPathController.cls
Public class BLP_CreateTrainingPathController{
    
    public string serchCurriculumStr{get;set;}
    public string serchCourseStr{get;set;}
    
    public BLP_CreateTrainingPathController(Apexpages.Standardcontroller stdController){
        serchCurriculumStr = '';
        serchCourseStr = 'c';
    }
    
    public list<CurriculumDataWrapper> getSearchedCurriculums(){
        list<CurriculumDataWrapper> curriculum = new list<CurriculumDataWrapper>();
        if(serchCurriculumStr != null && serchCurriculumStr != ''){
            serchCurriculumStr = '%' + serchCurriculumStr + '%';
            list<BLP_Course_To_Curriculum__c> ctcList = [select id, name, BLP_Curriculum__r.name, BLP_Curriculum__r.BLP_Curriculum_Title__c, BLP_Curriculum__c from BLP_Course_To_Curriculum__c where BLP_Curriculum__r.name like : serchCurriculumStr];
            for(BLP_Course_To_Curriculum__c ctc : ctcList){
                if(ctc.BLP_Curriculum__c != null && ctc.BLP_Curriculum__r.name != null){
                    CurriculumDataWrapper wrap = new CurriculumDataWrapper();
                    wrap.curriculumName = ctc.BLP_Curriculum__r.name;
                    wrap.curriculumTitle = ctc.BLP_Curriculum__r.BLP_Curriculum_Title__c;
                    wrap.order = 1;
                    curriculum.add(wrap);
                }
            }
        }
        return curriculum;
    }
    
    public list<CourseDataWrapper> getSearchedCourses(){
        list<CourseDataWrapper> courses = new list<CourseDataWrapper>();
        if(serchCourseStr != null && serchCourseStr != ''){
            serchCourseStr = '%' + serchCourseStr + '%';
            list<BLP_Course__c> couList = [select id, name, BLP_Course_Name__c from BLP_Course__c where BLP_Course_Name__c like : serchCourseStr];
            for(BLP_Course__c cou : couList){
                if(cou.BLP_Course_Name__c != null){
                    CourseDataWrapper wrap = new CourseDataWrapper();
                    wrap.courseName = cou.BLP_Course_Name__c;
                    wrap.courseId = cou.Id;
                    courses.add(wrap);
                }
            }
        }
        return courses;
    }
    
    public class CurriculumDataWrapper{
        Public string curriculumName{get;set;}
        Public string curriculumTitle{get;set;}
        Public integer order{get;set;}
        
    }
    
    public class CourseDataWrapper{
        Public string courseName{get;set;}
        Public string courseId{get;set;}
        
    }
}